/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author HEMANATHAN
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    
    String filename = null;
    private String gender;
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public AddEmployee() {
        initComponents();
        
        
                
        Icon i = AddempBackgr.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(AddempBackgr.getWidth(), AddempBackgr.getHeight(), Image.SCALE_SMOOTH);
        AddempBackgr.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtAttach = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        ImgIconAddEmp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmpID = new javax.swing.JTextField();
        EmpName = new javax.swing.JTextField();
        EmpDob = new javax.swing.JTextField();
        EmpEmail = new javax.swing.JTextField();
        EmpContact = new javax.swing.JTextField();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EmpDept = new javax.swing.JTextField();
        EmpDesig = new javax.swing.JTextField();
        EmpSal = new javax.swing.JTextField();
        EmpHiRDat = new javax.swing.JTextField();
        ClrData = new javax.swing.JButton();
        AddData = new javax.swing.JButton();
        AddempBackgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);

        BtAttach.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        BtAttach.setIcon(new javax.swing.ImageIcon("C:\\Users\\HEMANATHAN\\Downloads\\project\\Images\\attach.png")); // NOI18N
        BtAttach.setText("Attach");
        BtAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAttachActionPerformed(evt);
            }
        });
        jPanel1.add(BtAttach);
        BtAttach.setBounds(244, 250, 91, 27);

        ImgIconAddEmp.setBackground(new java.awt.Color(0, 0, 0));
        ImgIconAddEmp.setPreferredSize(new java.awt.Dimension(100, 100));

        jDesktopPane1.setLayer(ImgIconAddEmp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgIconAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgIconAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(192, 88, 190, 144);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Emloyee ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(22, 295, 106, 28);

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Emloyee Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(22, 341, 106, 28);

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOB");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(22, 387, 106, 28);

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(22, 433, 106, 28);

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(22, 479, 106, 28);

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(22, 513, 106, 28);
        jPanel1.add(EmpID);
        EmpID.setBounds(134, 298, 139, 22);

        EmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNameActionPerformed(evt);
            }
        });
        jPanel1.add(EmpName);
        EmpName.setBounds(134, 344, 139, 22);

        EmpDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpDobActionPerformed(evt);
            }
        });
        jPanel1.add(EmpDob);
        EmpDob.setBounds(134, 390, 139, 22);
        jPanel1.add(EmpEmail);
        EmpEmail.setBounds(134, 436, 139, 22);
        jPanel1.add(EmpContact);
        EmpContact.setBounds(134, 482, 139, 22);

        MaleRB.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        MaleRB.setForeground(new java.awt.Color(255, 255, 255));
        MaleRB.setText("Male");
        MaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBActionPerformed(evt);
            }
        });
        jPanel1.add(MaleRB);
        MaleRB.setBounds(134, 517, 57, 20);

        FemaleRB.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        FemaleRB.setForeground(new java.awt.Color(255, 255, 255));
        FemaleRB.setText("Female");
        FemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRBActionPerformed(evt);
            }
        });
        jPanel1.add(FemaleRB);
        FemaleRB.setBounds(197, 517, 76, 20);

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(324, 295, 83, 28);

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Designation");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(324, 341, 83, 28);

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salary");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(324, 387, 83, 28);

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HiredDate");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(324, 433, 83, 28);

        EmpDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpDeptActionPerformed(evt);
            }
        });
        jPanel1.add(EmpDept);
        EmpDept.setBounds(425, 298, 147, 22);
        jPanel1.add(EmpDesig);
        EmpDesig.setBounds(425, 344, 147, 22);
        jPanel1.add(EmpSal);
        EmpSal.setBounds(425, 390, 147, 22);
        jPanel1.add(EmpHiRDat);
        EmpHiRDat.setBounds(425, 436, 147, 22);

        ClrData.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        ClrData.setText("Clear");
        ClrData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClrDataActionPerformed(evt);
            }
        });
        jPanel1.add(ClrData);
        ClrData.setBounds(330, 482, 168, 22);

        AddData.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        AddData.setText("Add");
        AddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataActionPerformed(evt);
            }
        });
        jPanel1.add(AddData);
        AddData.setBounds(330, 516, 168, 22);

        AddempBackgr.setIcon(new javax.swing.ImageIcon("C:\\Users\\HEMANATHAN\\Downloads\\project\\pngtree-abstract-technology-background-line-high-tech-electricity-image_430309.jpg")); // NOI18N
        jPanel1.add(AddempBackgr);
        AddempBackgr.setBounds(0, 0, 600, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(ImgIconAddEmp.getWidth(), ImgIconAddEmp.getHeight(), Image.SCALE_DEFAULT));
        ImgIconAddEmp.setIcon(imageIcon);
        
    }//GEN-LAST:event_BtAttachActionPerformed

    private void EmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpNameActionPerformed

    private void EmpDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpDobActionPerformed

    private void FemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRBActionPerformed
        // TODO add your handling code here:
        gender = "female";
        MaleRB.setSelected(false);
        FemaleRB.setSelected(true);
    }//GEN-LAST:event_FemaleRBActionPerformed

    private void EmpDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpDeptActionPerformed

    private void ClrDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClrDataActionPerformed
        // TODO add your handling code here:
        EmpID.setText("");
        EmpName.setText("");
        EmpDob.setText("");
        EmpEmail.setText("");
        EmpDept.setText("");
        EmpContact.setText("");
        EmpDesig.setText("");
        EmpSal.setText("");
        EmpHiRDat.setText("");
        ImgIconAddEmp.setIcon(null);
        //MaleRB.setAction(null);
        //FemaleRB.setAction(null);
    }//GEN-LAST:event_ClrDataActionPerformed

    private void AddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataActionPerformed
        // TODO add your handling code here:
        conn = Db.dbConnection();
        
        String query = "insert into addstaffinfo (id,name,dob,email,contact,gender,department,designation,salary,hiredate,image) "
                + "values(?,?,?,?,?,?,?,?,?,?,?)";
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,EmpID.getText());
            ps.setString(2,EmpName.getText());
            ps.setString(3,EmpDob.getText());
            ps.setString(4,EmpEmail.getText());
            ps.setString(5,EmpContact.getText());
            ps.setString(6,gender);
            ps.setString(7,EmpDept.getText());
            ps.setString(8,EmpDesig.getText());
            ps.setString(9,EmpSal.getText());
            ps.setString(10,EmpHiRDat.getText());
            ps.setString(11,filename);
            
            ps.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_AddDataActionPerformed

    private void MaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBActionPerformed
        // TODO add your handling code here:
        gender = "male";
        MaleRB.setSelected(true);
        FemaleRB.setSelected(false);
        //r_female.setSelected(true);
        //r_male.setSelected(false);
    }//GEN-LAST:event_MaleRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddData;
    private javax.swing.JLabel AddempBackgr;
    private javax.swing.JButton BtAttach;
    private javax.swing.JButton ClrData;
    private javax.swing.JTextField EmpContact;
    private javax.swing.JTextField EmpDept;
    private javax.swing.JTextField EmpDesig;
    private javax.swing.JTextField EmpDob;
    private javax.swing.JTextField EmpEmail;
    private javax.swing.JTextField EmpHiRDat;
    private javax.swing.JTextField EmpID;
    private javax.swing.JTextField EmpName;
    private javax.swing.JTextField EmpSal;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JLabel ImgIconAddEmp;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
